# Generated by Django 3.2.7 on 2021-10-04 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mascota',
            name='id',
        ),
        migrations.AddField(
            model_name='mascota',
            name='folio',
            field=models.CharField(default='', max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='mascota',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='mascotas/'),
        ),
    ]
