# Generated by Django 3.2.7 on 2021-10-04 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0002_auto_20211003_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='folio',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
